import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative text-gray-100">
        <main className="flex-1 flex flex-col">
          {children}
        </main>
        
        {/* Global Footer */}
        <footer className="w-full py-6 text-center text-gray-400 mt-auto bg-black/10 backdrop-blur-sm z-10 border-t border-white/5">
          <p className="text-sm font-medium tracking-wide">
            Made with <span className="text-red-500 animate-pulse inline-block mx-1 text-base">❤️</span> by Sumon
          </p>
        </footer>
      </body>
    </html>
  );
}
